### PR TITLE
Adds Android export (debug and release)

### LINKED ISSUE #18: Support android exports
Just polling how hard it would be to add a way to export to Android?
Would it be a lot of work or is it just a single text line away?

### PR DESCRIPTION
**Pull request by HunterNN**
I added Android export. Closes #18
It allows to quickly export a debug version (generates automatically a debug.keystore) and to export an apk with a own keystore which is stored as a GitLab CI variable. At the moment it doesn't provide GitHub examples.

### CODE REVIEW

**Comment by HunterNN** [comment]
I also uploaded a version of the image to docker hub: [hunternn/godot-ci](https://hub.docker.com/r/hunternn/godot-ci)
It will be removed after implementation of android export in the main docker image.

**Comment by asheraryam** [comment]
Looks good to me. If the docker image size increases too much we can move it to a separate docker file later like with mono.

**Comment by HunterNN** [comment]
Your right. 
The current image is at 939MB while my android version is at 1.31GB.
One improvement is to use `openjdk-8-jdk-headless` instead of `openjdk-8-jdk` which brings the size of the image down to 1.12GB.

**Comment by asheraryam** [comment]
@HunterNN I compared the images on Dockerhub and both are lower than in your comment (perhaps you were comparing local builds? The ones on Dockerhub are compressed).

Latest regular image: 555MB
Latest hunterNN image 616MB
Latest mono image: 1.56GB

The difference of 100MB is okay, there is no need to split into an Android-specific image. The size difference is much much smaller than the mono image.

@aBARICHELLO I believe this is safe to merge, it's similar to the Android images I tested before. I trust that OP has also tested it.

**Comment by HunterNN** [comment]
Yes, sorry I was talking about the local size. That's great to hear.
I tested it on GitLab. The last test can be found [here](https://gitlab.com/Hunter99/godot-ci-test/-/pipelines/198657052).
The itch.io-Deploy fails, since I don't provide the variables in this repo. The production export is made with a test keystore.
The artifact of the production release can be downloaded [here](https://gitlab.com/Hunter99/godot-ci-test/-/jobs/775059468/artifacts/download)

As it looks like the additional installation of android sdk is not needed when building with godot. Only adb and the jdk tools have to be present. My guess is that godot is using gradle to build the apk or dex files and gradle will install android sdk in a separated step. Maybe this could change, if a developer wants to provide their own apk template. But I haven't had a look on it yet.

**Comment by aBARICHELLO** [comment]
Looks good to me, APK runs fine and the size difference is minimal as @asheraryam said.
Thanks for the contribution!

**Pull request merged**
