### PR TITLE
feature(lfs): add dependency to image

### PR DESCRIPTION
**Pull request by lallmon**
This image is great, but my project uses LFS, and without it, causes builds to think that assets are corrupt.

Would love to get this added here, and the image pushed to Dockerhub.

If not, you guys have any suggestions on how to use your Dockerfile in an easy way?

### CODE REVIEW

**Comment by asheraryam** [comment]
Nice catch! Surprised I didn't have trouble with this in my own projects.

Can you also add the same change to the mono dockerfile?

**Comment by lallmon** [comment]
@asheraryam added!

**Comment by aBARICHELLO** [comment]
Thanks!

**Comment by lallmon** [comment]
@aBARICHELLO No problem! How often do you push your image up to dockerhub?

**Comment by aBARICHELLO** [comment]
Latest image is set to autobuild, I'll rebase the changes to 3.2.3 in a few hours

**Comment by lallmon** [comment]
:boom: 

:pray:

**Comment by aBARICHELLO** [comment]
image
Done, should be ready in an hour or so...

**Pull request merged**
