### PR TITLE
Add link to Mono version

### PR DESCRIPTION
**Pull request by asheraryam**
Hello, I made a Mono version a few weeks ago and it's been working great.

It's hard enough finding our repos so I thought to add a link for those who might need it.

### CODE REVIEW

**Comment by Calinou** [comment]
In the future, we could merge the two repositories together so the Mono version is available in the same repository. This would decrease fragmentation and make things easier to find overall.

**Comment by aBARICHELLO** [comment]
I've sent him an email. I think that's the best option.

**Comment by asheraryam** [comment]
Hello @aBARICHELLO ! I got your email and I agree with merging the repos.

I'm afraid I don't use Telegram so we can coordinate here on github, via email, or you can ping me on discord where I'm always online (asheraryam#3800).

**Comment by asheraryam** [comment]
Superseded by https://github.com/aBARICHELLO/godot-ci/pull/16

**Pull request closed without merging**
